const fs = require("fs")
//fs.writeFileSync("adfar.txt","Starting node modules adfaffafafaf")
//fs.appendFileSync("adfar.txt"," I lovec nodejs")
// const data = fs.readFileSync("Amir.txt")
// const string_data = data.toString()
// console.log(string_data)
// fs.unlinkSync("Adfar/Amir.txt")
fs.rmdirSync("Adfar")
//fs.renameSync("adfar.txt","Amir.txt")